const sliderList = [
  {
    img: "images/carousel/images.jfif",
    id: 1,
    descriptionA: "5 bds ",
    descriptionB: "3 ba",
    descriptionC: "1, 600 sqft",
    descriptionD: "Active",
    descriptionF: "MLS ID #11476694 , RE MAX CITY",
    price: "$350,000",
    descriptionUnder: "1109 N Ridgeway Ave, Chikago",
    imgLike: "images/carousel/freeIcon.png",
    imgLikeT: "images/carousel/freeBlue.png",
    imgDesk: "San Mateo"
  },
  {
    img: "images/carousel/images.jfif",
    id: 2,
    descriptionA: "5 bds ",
    descriptionB: "3 ba",
    descriptionC: "1, 600 sqft",
    descriptionD: "Active",
    descriptionF: "MLS ID #11476694 , RE MAX CITY",
    price: "$350,000",
    descriptionUnder: "1109 N Ridgeway Ave, Chikago",
    imgLike: "images/carousel/freeIcon.png",
    imgLikeT: "images/carousel/freeBlue.png",
    imgDesk: "Santa Clara"
  },
  {
    img: "images/carousel/images.jfif",
    id: 3,
    descriptionA: "5 bds ",
    descriptionB: "3 ba",
    descriptionC: "1, 600 sqft",
    descriptionD: "Active",
    descriptionF: "MLS ID #11476694 , RE MAX CITY",
    price: "$350,000",
    descriptionUnder: "1109 N Ridgeway Ave, Chikago",
    imgLike: "images/carousel/freeIcon.png",
    imgLikeT: "images/carousel/freeBlue.png",
    imgDesk: " Alphabet's Google"
  },
  {
    img: "images/carousel/images.jfif",
    id: 4,
    descriptionA: "5 bds ",
    descriptionB: "3 ba",
    descriptionC: "1, 600 sqft",
    descriptionD: "Active",
    descriptionF: "MLS ID #11476694 , RE MAX CITY",
    price: "$350,000",
    descriptionUnder: "1109 N Ridgeway Ave, Chikago",
    imgLike: "images/carousel/freeIcon.png",
    imgLikeT: "images/carousel/freeBlue.png",
    imgDesk: "Silicon Valley"
  },
  {
    img: "images/carousel/images.jfif",
    id: 5,
    descriptionA: "5 bds ",
    descriptionB: "3 ba",
    descriptionC: "1, 600 sqft",
    descriptionD: "Active",
    descriptionF: "MLS ID #11476694 , RE MAX CITY",
    price: "$350,000",
    descriptionUnder: "1109 N Ridgeway Ave, Chikago",
    imgLike: "images/carousel/freeIcon.png",
    imgLikeT: "images/carousel/freeBlue.png",
    imgDesk: "Mobile Payments",
    imgDeskNull: ""
  },
  {
    img: "images/carousel/images.jfif",
    id: 6,
    descriptionA: "5 bds ",
    descriptionB: "3 ba",
    descriptionC: "1, 600 sqft",
    descriptionD: "Active",
    descriptionF: "MLS ID #11476694 , RE MAX CITY",
    price: "$350,000",
    descriptionUnder: "1109 N Ridgeway Ave, Chikago",
    imgLike: "images/carousel/freeIcon.png",
    imgLikeT: "images/carousel/freeBlue.png",
    imgDesk: "Enterprise Software"
  },
  {
    img: "images/carousel/images.jfif",
    id: 7,
    descriptionA: "5 bds ",
    descriptionB: "3 ba",
    descriptionC: "1, 600 sqft",
    descriptionD: "Active",
    descriptionF: "MLS ID #11476694 , RE MAX CITY",
    price: "$350,000",
    descriptionUnder: "1109 N Ridgeway Ave, Chikago",
    imgLike: "images/carousel/freeIcon.png",
    imgLikeT: "images/carousel/freeBlue.png",
    imgDesk: "Belle Haven"
  },
  {
    img: "images/carousel/images.jfif",
    id: 8,
    descriptionA: "5 bds ",
    descriptionB: "3 ba",
    descriptionC: "1, 600 sqft",
    descriptionD: "Active",
    descriptionF: "MLS ID #11476694 , RE MAX CITY",
    price: "$350,000",
    descriptionUnder: "1109 N Ridgeway Ave, Chikago",
    imgLike: "images/carousel/freeIcon.png",
    imgLikeT: "images/carousel/freeBlue.png",
    imgDesk: " San Jose"
  },
  {
    img: "images/carousel/images.jfif",
    id: 9,
    descriptionA: "5 bds ",
    descriptionB: "3 ba",
    descriptionC: "1, 600 sqft",
    descriptionD: "Active",
    descriptionF: "MLS ID #11476694 , RE MAX CITY",
    price: "$350,000",
    descriptionUnder: "1109 N Ridgeway Ave, Chikago",
    imgLike: "images/carousel/freeIcon.png",
    imgLikeT: "images/carousel/freeBlue.png",
    imgDesk: "San Joe"
  },
  {
    img: "images/carousel/images.jfif",
    id: 10,
    descriptionA: "5 bds ",
    descriptionB: "3 ba",
    descriptionC: "1, 600 sqft",
    descriptionD: "Active",
    descriptionF: "MLS ID #11476694 , RE MAX CITY",
    price: "$350,000",
    descriptionUnder: "1109 N Ridgeway Ave, Chikago",
    imgLike: "images/carousel/freeIcon.png",
    imgLikeT: "images/carousel/freeBlue.png",
    imgDesk: "Willow Glen"
  }
];

export default sliderList;
